### PR TITLE
Feature: ability to pass address from the url

### PR DESCRIPTION
**Pull request by peronczyk**
This change allows the user to open the faucet app with additional Query String param `address`. The value of this param will be passed to the recipient address.

It is related to this change done within the SH Wallet: https://github.com/aeternity/superhero-wallet/pull/2064/files#diff-1f9a257569ede6dcde62c105e97bb3cb14b905782053859cd3decde80f8a2605R96

### CODE REVIEW

**Comment by marc0olo** [comment]
@mmpetarpeshev @dincho has this faucet finally been 100% replaced when it comes to deployments? then I would suggest to archive it finally 🙄 

@peronczyk the faucet has been rewritten in js, see https://github.com/aeternity/aepp-faucet-nodejs

**Comment by peronczyk** [comment]
Thanks for letting me out @marc0olo . I strongly suggest to archive this to avoid further mistakes :)

**Comment by marc0olo** [comment]
as far as I can see the python faucet should be fully replaced meanwhile 🤔 

see last comment here: https://github.com/aeternity/aepp-faucet-nodejs/issues/9#issuecomment-1274627918


> Thanks for letting me out @marc0olo . I strongly suggest to archive this to avoid further mistakes :)

I fully agree ... but if you screen the history of comments you might understand why it hasn't been archived so far 🤣

**Comment by peronczyk** [comment]
OK @marc0olo . Meanwhile I created separate PR for this change within the nodejs repo: https://github.com/aeternity/aepp-faucet-nodejs/pull/18
Closing this PR...

**Pull request closed without merging**
