### PR TITLE
migration to js-sdk

### PR DESCRIPTION
**Pull request by marc0olo**
still work in progress

### CODE REVIEW

**Comment by marc0olo** [comment]
@mradkov this is now more or less the 1:1 migration from python to javascript.

I am currently not sure about:
- which branch to use for the PR (`master` or `develop`)
- how the old release process looked like and how we handle the deployment
- whether we really need to allow CORS (which seemed to be an requirement in the past)

**Review by mradkov — APPROVED** [review]

**Comment by marc0olo** [comment]
@dincho @venimus can somebody of you tell us what that test in the docker cloud is about? I don't think sth. should break if we merge and deploy this state. but would be good to have someone of you have a look at it :)

**Comment by dincho** [comment]
I disagree a bit to reuse this repository to migrate to another language. Why ? Wouldn't it be much more clean to just create and use new repo ?

**Comment by dincho** [comment]
> @dincho @venimus can somebody of you tell us what that test in the docker cloud is about? I don't think sth. should break if we merge and deploy this state. but would be good to have someone of you have a look at it :)
> 
> edit:
> 
> * and as already mentioned I am not sure about the past release process 😅

We're not aware. It was managed by another team. No idea about the release process as well.

**Comment by marc0olo** [comment]
> I disagree a bit to reuse this repository to migrate to another language. Why ? Wouldn't it be much more clean to just create and use new repo ?

sounds reasonable. we might follow that suggestion

> We're not aware. It was managed by another team. No idea about the release process as well.

I don't like this answer. but it is like it is. thanks for lettings us know!

**Comment by dincho** [comment]
> I don't like this answer. but it is like it is. thanks for lettings us know!

I'm aware of the deployment process tho, someone somehow pushed to dockerhub and we take care from there :)

**Comment by marc0olo** [comment]
closing this in favor of https://github.com/aeternity/aepp-faucet-nodejs/pull/2

**Pull request closed without merging**
